Repository earthlab/earthpy, pull requests merged in 2018-12, with the labels that each got.

#135 [tests] add non gdf tests to clip test file 100% coverage
  earthpy/clip.py
  earthpy/tests/test_clip.py
  earthpy/tests/test_mask.py
Labels: package structure & testing, review requested

#128 Adding pytest fixtures for re-used test data
  README.md
  earthpy/tests/conftest.py
  earthpy/tests/test_clip.py
  earthpy/tests/test_mask.py
  earthpy/tests/test_spatial.py
Labels: enhancement, package structure & testing

#122 [tests] plot_band tests - 100% coverage yay!!
  .travis.yml
  earthpy/spatial.py
  earthpy/tests/test_plot.py
Labels: package structure & testing

#161 blackifying all the things
  docs/conf.py
  earthpy/__init__.py
  earthpy/clip.py
  earthpy/io.py
  earthpy/mask.py
  earthpy/spatial.py
  earthpy/tests/conftest.py
  earthpy/tests/test_clip.py
  earthpy/tests/test_mask.py
  earthpy/tests/test_plot.py
  earthpy/tests/test_spatial.py
  earthpy/utils.py
  setup.py
Labels: changes requested

#147 Tests for colorbar height and a few minor updates
  earthpy/spatial.py
  earthpy/tests/test_plot.py
Labels: changes requested, review requested

#151 Run example code in docs with doctest
  .travis.yml
  README.md
  docs/conf.py
  docs/get-started.rst
  docs/spatial-raster.rst
  docs/spatial-vector.rst
  earthpy/__init__.py
  earthpy/clip.py
  earthpy/example-data/README.md
  earthpy/example-data/blue.tif
  earthpy/example-data/colorado-counties.geojson
  earthpy/example-data/colorado-glaciers.geojson
  earthpy/example-data/continental-div-trail.geojson
  earthpy/example-data/epsg.json
  earthpy/example-data/green.tif
  earthpy/example-data/red.tif
  earthpy/example-data/rmnp-dem.tif
  earthpy/example-data/rmnp-rgb.tif
  earthpy/example-data/rmnp.dbf
  earthpy/example-data/rmnp.prj
  earthpy/example-data/rmnp.shp
  earthpy/example-data/rmnp.shx
  earthpy/io.py
  earthpy/mask.py
  earthpy/spatial.py
  earthpy/tests/test_io.py
  setup.py
Labels: documentation, enhancement, package structure & testing, review requested

#140 Modify normalized_diff and add tests
  docs/spatial-raster.rst
  earthpy/spatial.py
  earthpy/tests/test_spatial.py
Labels: changes requested

#182 Generate API docs with Napoleon
  .travis.yml
  CONTRIBUTING.rst
  Makefile
  docs/conf.py
  docs/earthpy.rst
  docs/ignoreme/spatial-raster.rst
  docs/ignoreme/spatial-vector.rst
  docs/index.rst
  docs/modules.rst
  earthpy/__init__.py
  earthpy/clip.py
  earthpy/mask.py
  earthpy/spatial.py
Labels: documentation, package structure & testing, review requested
