Repository earthlab/earthpy, pull requests merged in 2018-10, with the labels that each got.

#18 Support testing on Travis CI + Codecov
  .travis.yml
  README.md
  earthpy/tests/__init__.py
  earthpy/tests/test_spatial.py
  environment.yml
Labels: enhancement

#47 Add contributing file - based upon geopandas and pandas for now
  .gitignore
  CONTRIBUTING.md
Labels: package structure & testing

#80 Add .rst documentation for hillshade function in spatial.py AND add .rst documentation for crop_image function in spatial.py
  docs/spatial-raster.rst
Labels: changes requested

#73 Updated spatial-raster.rst and spatial-vector.rst with new documenatation
  docs/spatial-raster.rst
  docs/spatial-vector.rst
Labels: changes requested

#95 [code] Updating data download, and a few import fixes
  earthpy/io.py
  earthpy/spatial.py
  setup.py
Labels: enhancement

#78 Added docstring to clip_shp and add .rst documentation to clip_point
  docs/spatial-vector.rst
  earthpy/clip.py
Labels: changes requested
