Repository earthlab/earthpy, pull requests merged in 2019-06, with the labels that each got.

#344 added code and tests for mismatched arrays, CRS, and Affine xform in …
  CHANGELOG.md
  earthpy/spatial.py
  earthpy/tests/conftest.py
  earthpy/tests/test_stack.py
Labels: enhancement

#342 Add crop_all Function to earthpy - new functionality
  CHANGELOG.md
  earthpy/spatial.py
  earthpy/tests/conftest.py
  earthpy/tests/test_crop_all.py
  earthpy/tests/test_crop_image.py
  examples/plot_raster_stack_crop.py
Labels: enhancement

#361 Hillshade vignette
  CHANGELOG.md
  README.md
  docs/get-started.rst
  earthpy/io.py
  examples/plot_dem_hillshade.py
Labels: changes requested, documentation

#370 Add Week 13 twitter data to earthpy as a key in get_data
  CHANGELOG.md
  docs/get-started.rst
  earthpy/io.py
Labels: enhancement

#371 Data description RST
  CHANGELOG.md
  docs/earthpy-data-subsets.rst
  docs/index.rst
Labels: documentation

#366 Histogram vignette
  CHANGELOG.md
  README.md
  examples/plot_bands_functionality.py
  examples/plot_hist_functionality.py
Labels: documentation
