Repository earthlab/earthpy, pull requests merged in 2019-03, with the labels that each got.

#251 Remove line for including package data to fix PyPI install issue
  setup.py
Labels: review requested

#210 Modify hillshade function and add tests
  earthpy/spatial.py
  earthpy/tests/test_hillshade.py
Labels: changes requested

#244 Test across versions and platforms
  .gitignore
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.rst
  README.md
  appveyor.yml
  dev-requirements.txt
  docs/earthpy.rst
  earthpy/io.py
  earthpy/tests/test_plot_rgb.py
  environment.yml
  setup.py
  tox.ini
Labels: enhancement, package structure & testing, review requested

#283 Test earthpy on OS X with Travis CI
  .travis.yml
  .travis/install.sh
  .travis/test.sh
  CHANGELOG.md
  tox.ini
Labels: enhancement, package structure & testing

#290 Remove download from setup.py
  setup.py
Labels: review requested

#294 Clean up API documentation
  Makefile
  docs/api.rst
  docs/api/earthpy-data.rst
  docs/api/earthpy.clip.rst
  docs/api/earthpy.io.rst
  docs/api/earthpy.mask.rst
  docs/api/earthpy.plot.rst
  docs/api/earthpy.rst
  docs/api/earthpy.spatial.rst
  docs/conf.py
  docs/earthpy.rst
  docs/index.rst
  docs/modules.rst
  earthpy/__init__.py
  earthpy/clip.py
  earthpy/io.py
  earthpy/mask.py
  earthpy/plot.py
  earthpy/spatial.py
Labels: documentation, enhancement
