Repository earthlab/earthpy, pull requests merged in 2019-05, with the labels that each got.

#320 Conditional skip tests on CI
  earthpy/tests/test_io.py
Labels: package structure & testing, review requested

#324 Add URL to io.py for landsat vignette data
  CHANGELOG.md
  docs/get-started.rst
  earthpy/io.py
Labels: changes requested

#317 Clip multi point line and polygon features
  CHANGELOG.md
  earthpy/clip.py
  earthpy/tests/test_clip.py
Labels: changes requested, enhancement, review requested

#307 Vignette #3 Creation, Stack and Crop Raster
  CHANGELOG.md
  CONTRIBUTING.rst
  README.md
  examples/plot_raster_stack_crop.py
Labels: enhancement

#336 Update NDVI vignette to use smaller vignette dataset
  examples/plot_calculate_classify_ndvi.py
Labels: documentation

#321 Vignette #5, Plot Bands
  CHANGELOG.md
  README.md
  examples/plot_bands_functionality.py
Labels: documentation

#328 Add plot_rgb vignette
  CHANGELOG.md
  README.md
  examples/plot_rgb.py
Labels: documentation
