Repository earthlab/earthpy, pull requests merged in 2019-02, with the labels that each got.

#188 Add bumpversion and automate PyPI deployment
  .travis.yml
  CONTRIBUTING.rst
  dev-requirements.txt
  setup.cfg
Labels: enhancement, review requested

#214 Doc string clean up for plot.py
  earthpy/plot.py
Labels: changes requested

#216 Docstring cleanup
  earthpy/clip.py
  earthpy/spatial.py
  earthpy/utils.py
Labels: changes requested

#226 Adding more info on deployment, doctest, and plots
  CONTRIBUTING.rst
  Makefile
  earthpy/plot.py
  earthpy/spatial.py
Labels: documentation, review requested

#231 Use setuptools in setup.py
  .gitignore
  setup.py
Labels: documentation, review requested

#248 Add code of conduct
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  docs/code-of-conduct.rst
  docs/conf.py
  docs/index.rst
Labels: documentation, enhancement
